### ISSUE TITLE
Last one, functionality. PLEASE HELP!

### ISSUE THREAD

**Issue by Jessica-Lee123** [Jessica-Lee123/web-design-2-independent-project#13]
@thatkidmadrid
@anna-pokhilenko
Hello, I understand this is a contrast colour issue, but I keep trying to fix it and nothing is working. I really want to keep the dark blue background, been trying to change all the font to white. Made the hover a light colour and white, but I can't change the text for any buttons. Thank you for your help! 
<img width="540" alt="Screen Shot 2021-12-11 at 11 04 13 PM" src="https://user-images.githubusercontent.com/77642609/145699820-eb64296b-d073-4b3e-9584-4e6138ea25da.png">

**Comment by thatkidmadrid** [comment]
This is because you don't have a hover nor focus state for the links in the navigation. Instead you have a hover state for the nav as a whole, which doesn't help the user see which of your navigation links is being hovered.

https://learn-the-web.algonquindesign.ca/topics/accessibility-for-design/#keyboard-focus-styles
This should give you an idea of how and why we are doing this

**Comment by thatkidmadrid** [comment]
![Screen Shot 2021-12-12 at 1 12 56 AM](https://user-images.githubusercontent.com/6340290/145702456-6c5c7bfb-f8f3-482b-b9c7-5ea44c356a4a.png)
FYI, I did check the contrast of the purples to confirm that it shouldn't be a contrast issue

**Comment by Jessica-Lee123** [comment]
@thatkidmadrid
Thank you so much for your response and for checking my contrast!
